### PR TITLE
fix windows detection

### PR DESCRIPTION
**Pull request by matsudamper**
The argument to `discoverAdbBinary` was the string `windows 11`.
"windows 11" == "win" was false.

Fixed an issue where `inheritIO` could not get from InputStream.

### CODE REVIEW

**Review by Malinskiy — APPROVED** [review]

**Comment by Malinskiy** [comment]
The issue is a due to device failure, rerunning the failed checks

**Comment by matsudamper** [comment]
Found another problem. 
Output will go to the console. I can't get it from inputStream.
I've verified this on Mac OS and Windows.
It fixed it by delete `inheritIO` or add `.redirectOutput(ProcessBuilder.Redirect.PIPE)` .
Should I open a another PR?
image

**Comment by Malinskiy** [comment]
We should fix both issues here.
I don't have/use windows so I can't reproduce this. Happy to fix it though :)

**Comment by matsudamper** [comment]
I am checking the operation. Windows and Mac OS.

**Comment by matsudamper** [comment]
@Malinskiy Operation check completed.

**Comment by Malinskiy** [comment]
There is a small problem I'm now seeing that we have to read from the streams in all the cases, including `exit code != 0`. Inherit IO solves this by just forwarding the streams, but since we're now not doing that, we have to read the output unconditionally for both stdout and stderr. It's fine to discard it, but the side-effect will be adb process lock since pipe will be overrun and not consumed by the adam's side. Quick search on GH gives [a sample](https://github.com/leonschreuder/kotlin-exec/blob/main/src/main/kotlin/io/github/leonschreuder/kotlinexec/Exec.kt#L36) of how to implement this.

**Comment by matsudamper** [comment]
I didn't know much about this part. Thank you.
Would this be ok?
https://github.com/Malinskiy/adam/pull/92/commits/7e19f5c1c317dbe6593aeef0965d6dc639ad72bc

**Comment by matsudamper** [comment]
> There is a small problem I'm now seeing that we have to read from the streams in all the cases, including exit code != 0

I forgot this.

**Comment by matsudamper** [comment]
Should I close stream when `process.exitValue() ! = 0` .
https://github.com/Malinskiy/adam/pull/92/commits/22c20d81dba74a0ce52ba7e085815d29f6204488

**Comment by Malinskiy** [comment]
Yes, I've created https://github.com/Malinskiy/adam/commit/3afc0f4d67cfe34e303d781d0e023b178996c340, please merge into your branch and we're good to go

**Comment by matsudamper** [comment]
completed.

**Comment by Malinskiy** [comment]
Thanks for being patient and diligent with this @matsudamper 
Congrats on your contribution :tada: :balloon:

**Comment by matsudamper** [comment]
thank you for reviewing.

**Pull request merged**
